---
collections:
  - name: awx.awx
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: cyberark.pas
  - name: community.hashi_vault
  - name: community.dns
  - name: community.vmware
  - name: vmware.vmware_rest
